os: 
 - linux 
language: generic 
sudo: required 
dist: trusty 
osx_image: xcode7.3 
before_install:
 - echo "deb [trusted=yes] http://apt.zewo.io/deb ./" | sudo tee --append /etc/apt/sources.list
 - apt-get update
 - apt-get install zewo
install: 
 - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/5254525d9da56df29346fd76e99529c22034d61d/Scripts/install-swiftenv.sh)" 
 - swiftenv local DEVELOPMENT-SNAPSHOT-2016-02-08-a
 - export LD_LIBRARY_PATH=$(pwd)/.build/debug

script: 
 - swift build
